### ISSUE TITLE
The iscsi login state of  multiple gateway nodes is not consistent.

### ISSUE THREAD

**Issue by MIZZ122** [ceph/ceph-iscsi-cli#105]
kenel: 3.10.0-862.el7.x86_64
ceph_version: 12.2.5

gateway nodes: hikcs01,hikcs02
iscsi initiator: hikcs03

hikcs03:
    #iscsiadm -m session -P 3
    iSCSI Transport Class version 2.0-870
    iscsiadm: No active sessions

hikcs02:
    in /sys/kernel/config/target/iscsi/iqn.xxxxx/tpgt_2/acls/iqn.1994-05.com.redhat:78bcc
    #cat info
    No active iSCSI Session for Initiator Endpoint:iqn.1994-05.com.redhat:78bcc

hikcs01:
     in /sys/kernel/config/target/iscsi/iqn.xxxxx/tpgt_1/acls/iqn.1994-05.com.redhat:78bcc
    #cat info
    InitiatorName: iqn.1994-05.com.redhat:78bcc
    InitiatorAlias: hikcs03
    LIO Session ID: 11
    Session State: TARG_SESS_STATE_LOGGED_IN

**Comment by mikechristie** [comment]
That's not really something we can change. It is part of the protocol and/or kernel issue.

It is possible and valid that the target has not detected a connection/session does not exist on the initiator side because there is just no IO going on (nops could be disabled) and the initiator could have just dropped the connection without sending a LOGOUT first. The target then just does not get an indication that the session is gone until there is a relogin attempt.

**Comment by mikechristie** [comment]
Please reopen if you have something in the target side logs that indicate it has dropped the connection/session and the state info reported in that configfs file should be different from what is logged and/or in the target's kernel.

**Comment by mikechristie** [comment]
Oh yeah, if you do

echo "module target_core_mod +p" > /sys/kernel/debug/dynamic_debug/control 
echo "module iscsi_target_mod +p" > /sys/kernel/debug/dynamic_debug/control 

on the target then you can get some extra info from the kernel about the state of the session and possibly why it has not detected that the session has been removed on the initiator side.
