### ISSUE TITLE
How many luns supported under one host?

### ISSUE THREAD

**Issue by vatelzh** [ceph/ceph-iscsi-cli#52]

**Comment by mikechristie** [comment]
256.

For the ceph-iscsi-config I think we are limited to 256 due to some hard coded limits there. This was because the original kernel we worked with had that limit (RHEL 7.4 and below still has it for example), and so we never fixed it. Newer upstream kernels use 64 bit LUNs and have no internal hard coded limit, so we would just need to fix the hard coded 256/255 values in the code and add some checks for when older kernels throw errors.

**Comment by vatelzh** [comment]
Copy that, thanks for your answer.
